### ISSUE TITLE
You may encounter revokation

### ISSUE THREAD

**Issue by dol** [Eun/test.bi#1]
The C/A forum [Baseline Requirements](https://cabforum.org/baseline-requirements-documents/) states very clear that if a private key is publicly known the CA must revoke the certificates.
This happed to the [sslip.io](https://github.com/cunnie/sslip.io/issues/2) project.
I guess @jsha and @jcjones can support me regarding this issue.

It's a nice idea of you providing this service. But a publicly known private key could also be used to distribute malware. Let's encrypt has stated about this in a [blog post](https://letsencrypt.org/2015/10/29/phishing-and-malware.html).

Sorry to be the grinch.

**Comment by jcjones** [comment]
Anyone [who has access to the private key [ACME specification section 6.6]](https://ietf-wg-acme.github.io/acme/#rfc.section.6.6) can revoke this certificate. In fact, I just went to revoke it and found it already revoked; someone got there before me.

I think the intention here is good, but going to have to find a different way to accomplish the goal.

**Comment by Eun** [comment]
Good to know, thanks. I may provide another certificate soon. Without using letsencrypt. Maybe a commercial one.

Thoughts?

**Comment by Eun** [comment]
Oh, did I got this right that you can revoke any certificate by the private key?

**Comment by jsha** [comment]
@Eun: We've actually had a [recent thread on the Let's Encrypt forums](https://community.letsencrypt.org/t/a-public-cert-for-localdev-letsencryrpt-org/13504/7?u=jsha) about this topic. I completely understand the motivation, and appreciate your work, but this is the wrong approach.

Instead, I'd recommend you focus on helping to build really great tools that make it easy for people to install and trust a self-signed certificate for localhost, as I describe in the thread linked above.

Also, FYI, issuing certificates with the intent to publicly disclose the private key is a violation of the Let's Encrypt [Subscriber Agreement](https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf):

> You warrant that You have taken all appropriate, reasonable, and necessary steps to secure
and keep your Private Key secret.

**Comment by dol** [comment]
Thank you @jcjones and @jsha the insightfully explanation of this matter.
