### ISSUE TITLE
DNS mapping

### ISSUE THREAD

**Issue by julianxhokaxhiu** [Eun/test.bi#4]
Going through your README is not really clear how the DNS is mapped.

Shall I do it myself on my own hosts file? Is there a mapping on "127.0.0.1"?

Thanks in advance,
Julian

**Comment by Eun** [comment]
Yes, you should map the DNS by yourself using a custom DNS or hosts file.

**Comment by julianxhokaxhiu** [comment]
I see. Thanks!

Would you mind adding a paragraph that explains this in the README?
